async (page) => {
  const check = (condition, message) => { if (!condition) throw new Error(message); };
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('http://127.0.0.1:8001');
  check(await page.getByText('Compare methods', {exact:true}).count() === 1, 'Provide optional comparison controls');
  await page.getByText('Compare methods', {exact:true}).click();
  check(await page.getByRole('checkbox', {name:'Basic',exact:true}).isChecked(), 'Default to Basic');
  check(await page.getByRole('checkbox', {name:'Basic',exact:true}).isDisabled(), 'Keep at least one method');
  await page.getByRole('checkbox', {name:'Autocomplete',exact:true}).uncheck();
  let suggestions=0;
  const count = request => {if(request.url().includes('/api/suggestions?')) suggestions++;};
  page.on('request', count);
  await page.getByRole('combobox', {name:'Search cameras'}).fill('Sony');
  await page.getByRole('button', {name:'Search',exact:true}).click();
  await page.locator('.product-select').first().waitFor();
  check(suggestions===0, 'Disabled autocomplete must not request suggestions');
  check(await page.locator('.method-result').count()===1, 'One method gives one list');
  let searches=0;
  const countSearch = request => {if(request.url().endsWith('/api/compare')) searches++;};
  page.on('request', countSearch);
  await page.getByRole('checkbox', {name:'Hybrid',exact:true}).check();
  check(await page.locator('.method-result').count()===2, 'Two methods give two lists');
  await page.getByRole('checkbox', {name:'Full-text',exact:true}).check();
  await page.getByRole('checkbox', {name:'Vector',exact:true}).check();
  check(await page.locator('.method-result').count()===4, 'Four methods give four lists');
  check(searches===0, 'Changing comparison views must not repeat a search');
  check(await page.locator('.method-basic .product-select').count()>0, 'Basic should return literal Sony title matches');
  await page.locator('.method-basic .product-select').first().click();
  await page.getByRole('dialog').waitFor();
  await page.getByText('Basic evidence', {exact:true}).click();
  check((await page.getByRole('dialog').innerText()).includes('alphabetical'), 'Explain Basic ordering');
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:390,height:844});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), 'Comparison must not overflow the mobile page');
  for(const name of ['Hybrid','Full-text','Vector']) await page.getByRole('checkbox',{name,exact:true}).uncheck();
  check(await page.locator('.method-result').count()===1, 'Can return to calm single list');
  await page.getByRole('checkbox',{name:'Autocomplete',exact:true}).check();
  await page.getByRole('combobox',{name:'Search cameras'}).fill('son');
  await page.getByRole('listbox').waitFor();
  check(await page.getByRole('option').count()>0, 'Re-enabling autocomplete restores suggestions');
  page.off('request',count);page.off('request',countSearch);
  return {passed:true,checks:['default','nonempty selection','autocomplete off/on','one/two/four methods','cached view changes','Basic evidence','mobile layout']};
}
